fix: remove rollup warning & separate directives for each output chunk
huozhi/rollup-plugin-swc-preserve-directives pull request #2
Opened 2023-07-11 04:04 UTC by SukkaW

The PR does 2 things:

- Each output chunk will only have its separate directives.
  - This enables the server/client builds with different input entries
- Remove rollup warning about module-level directives.
  <img width="1587" alt="image" src="https://github.com/huozhi/rollup-plugin-swc-preserve-directives/assets/40715044/44e71d0c-f592-4aef-bd14-41e3fdcd01ef">

2023-07-13 07:19 UTC, SukkaW commented
ping @huozhi

2023-07-13 15:46 UTC, SukkaW commented
> Is that possible to use [onLog](https://rollupjs.org/plugin-development/#onlog) to fix ignore the warning?

Probably not. The warning from rollup is intentional, to let library developers know they should take actions. `rollup-swc-preserve-directives-plugin` is just one of the possible action that library authors could take.

> editing the code is bit tricky 

rollup official plugins also use `magic-string` to manipulate code, so I guess it is safe: https://github.com/search?q=repo%3Arollup%2Fplugins%20magic-string&type=code

> if you already found that `span` in swc might not be super reliable.

Actually it is a bug of the swc's JS API. And the swc team decides to ignore the issue, since in the next major version of swc (swc v2) there will be no `swc.parse` JS API at all anyway.

For now, we can use tests and snapshots to ensure the current workaround works reliably.

In the future PR, I will migrate away from `swc.parse` to use the rollup's built-in `this.parse` plugin API instead.

> Another reason is what if other plugin also checks the directives?

IMHO, the `rollup-swc-preserve-directives-plugin` should be added after every other plugin (especially after the swc/babel transformation).

In the future PR, I will add `order: 'post'` declaration to the `transform` hook : https://rollupjs.org/plugin-development/#build-hooks

2023-07-13 22:14 UTC, huozhi commented
> rollup official plugins also use magic-string to manipulate code, so I guess it is safe: [github.com/search?q=repo%3Arollup%2Fplugins%20magic-string&type=code](https://github.com/search?q=repo%3Arollup%2Fplugins%20magic-string&type=code)
it's not related to magic string but we're deleting the comment

>In the future PR, I will migrate away from swc.parse to use the rollup's built-in this.parse plugin API instead (which also has stable/reliable span).

that's also the purpose of this plugin that `swc.parse` is much faster than acorn parse and will have interpreter information.

2023-07-13 22:49 UTC, huozhi commented on src/index.ts
> +       * @swc/core's node span doesn't start with 0
I dont think this is a bug, I remember it starts from a large number because it's a pointer for sth. It doesn't have to be `0`, should be fine to remove the comments.

2023-07-14 02:35 UTC, SukkaW commented on src/index.ts
> +       * @swc/core's node span doesn't start with 0
> I dont think this is a bug, I remember it starts from a large number because it's a pointer for sth.

https://github.com/swc-project/swc/issues/1366#issuecomment-769534686
https://github.com/swc-project/swc/issues/1366#issuecomment-902455836

2023-07-14 02:38 UTC, SukkaW commented
> can you share more where did you se it's going to be deprecated?

https://github.com/swc-project/swc/issues/1366#issuecomment-900805854

> I want to remove `parse` and `print` with v2 of swc.
> I'm going to provide a rust-based plugin API instead.

https://github.com/swc-project/swc/issues/1366#issuecomment-902455836

> Plugin api / parse / print is misdesigned and going to be removed in v2.
> In other words, AST will not be exposed to js world.

2023-07-14 09:20 UTC, huozhi commented on src/index.ts
> +       * @swc/core's node span doesn't start with 0
I mean the approach of calculate span distance is fine, we have also used that approach in nextjs before. We don't need to fix that and we don't need to FIXME comment. Could simplify it as "span doesn't start from 0" as a simple note

2023-07-14 11:29 UTC, SukkaW commented on src/index.ts
> +       * @swc/core's node span doesn't start with 0
IMHO, we might need to re-visit it in the future, and even refactor to use the rollup built-in parse API.

2023-07-14 12:00 UTC, huozhi requested changes
It's not a bug from swc, it doesn't harm to remove or block future refactor

2023-07-14 14:38 UTC, SukkaW commented on src/index.ts
> +       */
Done in [`c8d35fa` (#2)](https://github.com/huozhi/rollup-plugin-swc-preserve-directives/pull/2/commits/c8d35fad5b3133403bb291898d80a8d8dfc04197)

2023-07-14 21:46 UTC, huozhi approved these changes
Thanks!

2023-07-14 21:46 UTC, merged